### ISSUE TITLE
unknown option `dissociate'

### ISSUE THREAD

**Issue by nextofsearch** [ekho/capistrano-git-submodule-strategy#11]
Hi,

I am having an issue related to 'dissocate' option.
```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@ec2-107-21-74-129.compute-1.amazonaws.com: git exit status: 129
git stdout: Nothing written
git stderr: error: unknown option `dissociate'
```

**Comment by nextofsearch** [comment]
1.20 works well for me.

**Comment by ekho** [comment]
@nextofsearch you should upgrade your git if you can

**Comment by nextofsearch** [comment]
thanks. it works.

**Comment by nextofsearch** [comment]
Hi again,

It still happens with git 2.8.1 on Mac OS X. (It did not work previously. My mistake.)

**Comment by ekho** [comment]
Hmm, I can not reproduce on osx (((
```
$ git --version
git version 2.8.3

$ git clone --mirror git@github.com:ekho/capistrano-git-submodule-strategy.git testrep.mirror
Cloning into bare repository 'testrep.mirror'...
remote: Counting objects: 283, done.
remote: Total 283 (delta 0), reused 0 (delta 0), pack-reused 283
Receiving objects: 100% (283/283), 39.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (146/146), done.
Checking connectivity... done.

git clone --reference ./testrep.mirror --dissociate git@github.com:ekho/capistrano-git-submodule-strategy.git testrep
Cloning into 'testrep'...
Checking connectivity... done.
Counting objects: 277, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (117/117), done.
Writing objects: 100% (277/277), done.
Total 277 (delta 142), reused 277 (delta 142)
```

**Comment by ekho** [comment]
I think you should upgrade git on `ec2-107-21-74-129.compute-1.amazonaws.com`

**Comment by ekho** [comment]
@nextofsearch I added support git older than 2.3.0
Could you test it? I need to put into you Gemfile
```
gem 'rails', :git => "git://github.com/ekho/capistrano-git-submodule-strategy.git", :branch => "feature/compatibility-with-old-git"
```
and run
```
bundle update
```

**Comment by nextofsearch** [comment]
I guess, you meant your gem, not rails, right?

The patch you uploaded does not work even after I upgraded git to 2.8.3 on my server resulting the following error.

```
00:13 git:create_release
      01 mkdir -p /home/deployer/apps/worker/releases/20160530041956
    ✔ 01 deployer@52.23.241.122 0.393s
cap aborted!
NoMethodError: undefined method `capture' for #<Capistrano::Git:0x007fa6a427a540>
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/bundler/gems/capistrano-git-submodule-strategy-6cc4d39f723b/lib/capistrano/git-submodule-strategy.rb:40:in `release'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/capistrano-3.5.0/lib/capistrano/tasks/git.rake:64:in `block (5 levels) in <top (required)>'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:80:in `within'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/capistrano-3.5.0/lib/capistrano/tasks/git.rake:62:in `block (4 levels) in <top (required)>'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:88:in `with'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/capistrano-3.5.0/lib/capistrano/tasks/git.rake:61:in `block (3 levels) in <top (required)>'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/danolee/.rvm/gems/ruby-2.3.0@rails42/gems/sshkit-1.10.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => git:create_release
The deploy has failed with an error: undefined method `capture' for #<Capistrano::Git:0x007fa6a427a540>
```

After I upgraded gem on my server the latest version of gem just works. That's good for me for now.

Thanks!

**Comment by ekho** [comment]
> I guess, you meant your gem, not rails, right?
Yes, sorry =)

**Comment by ekho** [comment]
I fixed a fix =)
Use v0.1.22

**Comment by nextofsearch** [comment]
Great!
